//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoclient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auto", Namespace="http://schemas.datacontract.org/2004/07/WcfAuto")]
    [System.SerializableAttribute()]
    public partial class Auto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMalliID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AutonMerkkiID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Hinta1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Mittarilukema1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Moottorin_tilavuus1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PolttoaineID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Rekisteri_paivamaara1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VaritID1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMalliID1 {
            get {
                return this.AutonMalliID1Field;
            }
            set {
                if ((this.AutonMalliID1Field.Equals(value) != true)) {
                    this.AutonMalliID1Field = value;
                    this.RaisePropertyChanged("AutonMalliID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutonMerkkiID1 {
            get {
                return this.AutonMerkkiID1Field;
            }
            set {
                if ((this.AutonMerkkiID1Field.Equals(value) != true)) {
                    this.AutonMerkkiID1Field = value;
                    this.RaisePropertyChanged("AutonMerkkiID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Hinta1 {
            get {
                return this.Hinta1Field;
            }
            set {
                if ((this.Hinta1Field.Equals(value) != true)) {
                    this.Hinta1Field = value;
                    this.RaisePropertyChanged("Hinta1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Mittarilukema1 {
            get {
                return this.Mittarilukema1Field;
            }
            set {
                if ((this.Mittarilukema1Field.Equals(value) != true)) {
                    this.Mittarilukema1Field = value;
                    this.RaisePropertyChanged("Mittarilukema1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Moottorin_tilavuus1 {
            get {
                return this.Moottorin_tilavuus1Field;
            }
            set {
                if ((this.Moottorin_tilavuus1Field.Equals(value) != true)) {
                    this.Moottorin_tilavuus1Field = value;
                    this.RaisePropertyChanged("Moottorin_tilavuus1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolttoaineID1 {
            get {
                return this.PolttoaineID1Field;
            }
            set {
                if ((this.PolttoaineID1Field.Equals(value) != true)) {
                    this.PolttoaineID1Field = value;
                    this.RaisePropertyChanged("PolttoaineID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Rekisteri_paivamaara1 {
            get {
                return this.Rekisteri_paivamaara1Field;
            }
            set {
                if ((this.Rekisteri_paivamaara1Field.Equals(value) != true)) {
                    this.Rekisteri_paivamaara1Field = value;
                    this.RaisePropertyChanged("Rekisteri_paivamaara1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VaritID1 {
            get {
                return this.VaritID1Field;
            }
            set {
                if ((this.VaritID1Field.Equals(value) != true)) {
                    this.VaritID1Field = value;
                    this.RaisePropertyChanged("VaritID1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutonMerkki", Namespace="http://schemas.datacontract.org/2004/07/WcfAuto")]
    [System.SerializableAttribute()]
    public partial class AutonMerkki : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerkkinimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Merkkinimi {
            get {
                return this.MerkkinimiField;
            }
            set {
                if ((object.ReferenceEquals(this.MerkkinimiField, value) != true)) {
                    this.MerkkinimiField = value;
                    this.RaisePropertyChanged("Merkkinimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autonmallit", Namespace="http://schemas.datacontract.org/2004/07/WcfAuto")]
    [System.SerializableAttribute()]
    public partial class Autonmallit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MalliNimiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MerkkiIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MalliNimi {
            get {
                return this.MalliNimiField;
            }
            set {
                if ((object.ReferenceEquals(this.MalliNimiField, value) != true)) {
                    this.MalliNimiField = value;
                    this.RaisePropertyChanged("MalliNimi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MerkkiId {
            get {
                return this.MerkkiIdField;
            }
            set {
                if ((this.MerkkiIdField.Equals(value) != true)) {
                    this.MerkkiIdField = value;
                    this.RaisePropertyChanged("MerkkiId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Polttoaine", Namespace="http://schemas.datacontract.org/2004/07/WcfAuto")]
    [System.SerializableAttribute()]
    public partial class Polttoaine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolttoaineennimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Polttoaineennimi {
            get {
                return this.PolttoaineennimiField;
            }
            set {
                if ((object.ReferenceEquals(this.PolttoaineennimiField, value) != true)) {
                    this.PolttoaineennimiField = value;
                    this.RaisePropertyChanged("Polttoaineennimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vari", Namespace="http://schemas.datacontract.org/2004/07/WcfAuto")]
    [System.SerializableAttribute()]
    public partial class Vari : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VarinnimiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Varinnimi {
            get {
                return this.VarinnimiField;
            }
            set {
                if ((object.ReferenceEquals(this.VarinnimiField, value) != true)) {
                    this.VarinnimiField = value;
                    this.RaisePropertyChanged("Varinnimi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        bool TestDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDatabaseConnection", ReplyAction="http://tempuri.org/IService1/TestDatabaseConnectionResponse")]
        System.Threading.Tasks.Task<bool> TestDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveAuto", ReplyAction="http://tempuri.org/IService1/saveAutoResponse")]
        bool saveAuto(Autoclient.ServiceReference1.Auto biili);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/saveAuto", ReplyAction="http://tempuri.org/IService1/saveAutoResponse")]
        System.Threading.Tasks.Task<bool> saveAutoAsync(Autoclient.ServiceReference1.Auto biili);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/seurcar", ReplyAction="http://tempuri.org/IService1/seurcarResponse")]
        Autoclient.ServiceReference1.Auto seurcar(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/seurcar", ReplyAction="http://tempuri.org/IService1/seurcarResponse")]
        System.Threading.Tasks.Task<Autoclient.ServiceReference1.Auto> seurcarAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edellcar", ReplyAction="http://tempuri.org/IService1/edellcarResponse")]
        Autoclient.ServiceReference1.Auto edellcar(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/edellcar", ReplyAction="http://tempuri.org/IService1/edellcarResponse")]
        System.Threading.Tasks.Task<Autoclient.ServiceReference1.Auto> edellcarAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllAutoMakers", ReplyAction="http://tempuri.org/IService1/getAllAutoMakersResponse")]
        System.Collections.Generic.List<Autoclient.ServiceReference1.AutonMerkki> getAllAutoMakers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAllAutoMakers", ReplyAction="http://tempuri.org/IService1/getAllAutoMakersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.AutonMerkki>> getAllAutoMakersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAutoModels", ReplyAction="http://tempuri.org/IService1/getAutoModelsResponse")]
        System.Collections.Generic.List<Autoclient.ServiceReference1.Autonmallit> getAutoModels(int MerkkiId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAutoModels", ReplyAction="http://tempuri.org/IService1/getAutoModelsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.Autonmallit>> getAutoModelsAsync(int MerkkiId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFuel", ReplyAction="http://tempuri.org/IService1/GetFuelResponse")]
        System.Collections.Generic.List<Autoclient.ServiceReference1.Polttoaine> GetFuel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFuel", ReplyAction="http://tempuri.org/IService1/GetFuelResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.Polttoaine>> GetFuelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetColor", ReplyAction="http://tempuri.org/IService1/GetColorResponse")]
        System.Collections.Generic.List<Autoclient.ServiceReference1.Vari> GetColor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetColor", ReplyAction="http://tempuri.org/IService1/GetColorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.Vari>> GetColorAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Autoclient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Autoclient.ServiceReference1.IService1>, Autoclient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool TestDatabaseConnection() {
            return base.Channel.TestDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<bool> TestDatabaseConnectionAsync() {
            return base.Channel.TestDatabaseConnectionAsync();
        }
        
        public bool saveAuto(Autoclient.ServiceReference1.Auto biili) {
            return base.Channel.saveAuto(biili);
        }
        
        public System.Threading.Tasks.Task<bool> saveAutoAsync(Autoclient.ServiceReference1.Auto biili) {
            return base.Channel.saveAutoAsync(biili);
        }
        
        public Autoclient.ServiceReference1.Auto seurcar(int ID) {
            return base.Channel.seurcar(ID);
        }
        
        public System.Threading.Tasks.Task<Autoclient.ServiceReference1.Auto> seurcarAsync(int ID) {
            return base.Channel.seurcarAsync(ID);
        }
        
        public Autoclient.ServiceReference1.Auto edellcar(int ID) {
            return base.Channel.edellcar(ID);
        }
        
        public System.Threading.Tasks.Task<Autoclient.ServiceReference1.Auto> edellcarAsync(int ID) {
            return base.Channel.edellcarAsync(ID);
        }
        
        public System.Collections.Generic.List<Autoclient.ServiceReference1.AutonMerkki> getAllAutoMakers() {
            return base.Channel.getAllAutoMakers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.AutonMerkki>> getAllAutoMakersAsync() {
            return base.Channel.getAllAutoMakersAsync();
        }
        
        public System.Collections.Generic.List<Autoclient.ServiceReference1.Autonmallit> getAutoModels(int MerkkiId) {
            return base.Channel.getAutoModels(MerkkiId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.Autonmallit>> getAutoModelsAsync(int MerkkiId) {
            return base.Channel.getAutoModelsAsync(MerkkiId);
        }
        
        public System.Collections.Generic.List<Autoclient.ServiceReference1.Polttoaine> GetFuel() {
            return base.Channel.GetFuel();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.Polttoaine>> GetFuelAsync() {
            return base.Channel.GetFuelAsync();
        }
        
        public System.Collections.Generic.List<Autoclient.ServiceReference1.Vari> GetColor() {
            return base.Channel.GetColor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Autoclient.ServiceReference1.Vari>> GetColorAsync() {
            return base.Channel.GetColorAsync();
        }
    }
}
